DBManagementSystem/Controllers/DBTablesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DBManagementSystem.Models;

namespace DBManagementSystem.Controllers
{
    public class DBTablesController : Controller
    {
        private DBModel db = new DBModel();

        // GET: DBTables
        public ActionResult Index()
        {
            var dBTables = db.DBTables.Include(d => d.DBases);
            return View(dBTables.ToList());
        }

        // GET: DBTables/Details/5
        public ActionResult Details(int id)
        {
            DBTable dBTable = db.DBTables.Include(c => c.DBColumns).FirstOrDefault(c => c.ID == id);
            if (dBTable == null)
            {
                return HttpNotFound();
            }
            return View(dBTable);
        }

        // GET: DBTables/Create
        public ActionResult Create(int dbID)
        {
            var dbTable = new DBTable();
            dbTable.DBasesID = dbID;
            return PartialView(dbTable);
        }

        // POST: DBTables/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,DBasesID")] DBTable dBTable)
        {
            if (ModelState.IsValid)
            {
                db.DBTables.Add(dBTable);
                db.SaveChanges();
                return RedirectToAction("Details", "DBases", new { id = dBTable.DBasesID });
            }

            ViewBag.DBasesID = new SelectList(db.DBases, "ID", "Name", dBTable.DBasesID);
            return View(dBTable);
        }

        // GET: DBTables/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DBTable dBTable = db.DBTables.Find(id);
            if (dBTable == null)
            {
                return HttpNotFound();
            }
            ViewBag.DBasesID = new SelectList(db.DBases, "ID", "Name", dBTable.DBasesID);
            return View(dBTable);
        }

        // POST: DBTables/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,DBasesID")] DBTable dBTable)
        {
            if (ModelState.IsValid)
            {
                db.Entry(dBTable).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DBasesID = new SelectList(db.DBases, "ID", "Name", dBTable.DBasesID);
            return View(dBTable);
        }

        // GET: DBTables/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DBTable dBTable = db.DBTables.Find(id);
            if (dBTable == null)
            {
                return HttpNotFound();
            }
            return View(dBTable);
        }

        // POST: DBTables/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DBTable dBTable = db.DBTables.Find(id);
            db.DBTables.Remove(dBTable);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DBManagementSystem/Controllers/DBasesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DBManagementSystem.Models;

namespace DBManagementSystem.Controllers
{
    public class DBasesController : Controller
    {
        private DBModel db = new DBModel();

        // GET: DBases
        public ActionResult Index()
        {
            return View(db.DBases.Include(i => i.DBTables).ToList());
        }

        public ActionResult _Table()
        {
            return PartialView(db.DBases.Include(i => i.DBTables).ToList());
        }

        // GET: DBases/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DBases dBases = db.DBases.Include(c => c.DBTables).FirstOrDefault(c => c.ID == id);
            if (dBases == null)
            {
                return HttpNotFound();
            }
            return View(dBases);
        }

        // GET: DBases/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: DBases/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name")] DBases dBases)
        {
            if (ModelState.IsValid)
            {
                db.DBases.Add(dBases);
                db.SaveChanges();
                return PartialView("_Table", db.DBases.ToList());
            }

            return View(dBases);
        }

        // GET: DBases/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DBases dBases = db.DBases.Find(id);
            if (dBases == null)
            {
                return HttpNotFound();
            }
            return View(dBases);
        }

        // POST: DBases/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name")] DBases dBases)
        {
            if (ModelState.IsValid)
            {
                db.Entry(dBases).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(dBases);
        }

        // GET: DBases/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DBases dBases = db.DBases.Find(id);
            if (dBases == null)
            {
                return HttpNotFound();
            }
            return View(dBases);
        }

        // POST: DBases/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DBases dBases = db.DBases.Find(id);
            db.DBases.Remove(dBases);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DBManagementSystem/Views/DBases/Create.cshtml
@model DBManagementSystem.Models.DBases

@{
    Layout = null;
}

<h2>Create Database</h2>


@using (Ajax.BeginForm("Create", new AjaxOptions { UpdateTargetId = "dbContent" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label" })
        <div class="input-group">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", style = "max-width:none;" } })
            <span class="input-group-btn">
                <input type="submit" value="Create" class="btn btn-success" />
            </span>
        </div>
        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        <br />
    </div>
}

<div>
    @Ajax.ActionLink("Back to List", "_Table", null, new AjaxOptions { UpdateTargetId = "dbContent"}, new { @class = "btn btn-info" })
</div>

DBManagementSystem/Views/DBases/Delete.cshtml
@model DBManagementSystem.Models.DBases

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DBases</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DBManagementSystem/Views/DBases/Details.cshtml
@model DBManagementSystem.Models.DBases

@{
    Layout = null;
}
<p>
    @Ajax.ActionLink("Add New Table", "Create", "DBTables", new { dbID = Model.ID }, new AjaxOptions { UpdateTargetId = "tblContent" }, new { @class = "btn btn-info" })
</p>
<table class="table table-striped">
    <tr>
        <th>@Html.DisplayNameFor(model => model.DBTables.First().Name)</th>
        <th></th>
    </tr>
    @foreach (var item in Model.DBTables)
    {
        <tr>
            <td>@Html.ActionLink(item.Name, "Details", "DBTables", new { id = item.ID }, null)</td>
            <td class="text-right">
                <div class="btn-group" role="group">
                    @Html.ActionLink("Edit", "Edit", "DBTables", new { id = item.ID }, new { @class = "btn btn-warning" })
                    @Html.ActionLink("Delete", "Delete", "DBTables", new { id = item.ID }, new { @class = "btn btn-danger" })
                </div>
            </td>
        </tr>
    }
</table>

DBManagementSystem/Views/DBases/Edit.cshtml
@model DBManagementSystem.Models.DBases

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>DBases</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DBManagementSystem/Views/DBases/Index.cshtml
@model IEnumerable<DBManagementSystem.Models.DBases>

@{
    ViewBag.Title = "Index";
}

<h2>Database</h2>

<div class="row">
    <div class="col-sm-6" id="dbContent">
        @Html.Partial("_Table", Model)
    </div>
    <div class="col-sm-6" id="tblContent">
        @if (Model.Count() > 0)
        {
            @Html.Partial("Details", Model.First())
        }
    </div>
</div>

@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/scripts/jquery.unobtrusive-ajax.js")    
}

DBManagementSystem/Views/DBases/_Table.cshtml
@model IEnumerable<DBManagementSystem.Models.DBases>
@{ 
    Layout = null;
}
<p>
    @*@Html.ActionLink("Create New Database", "Create", null, new { @class = "btn btn-info"})*@
    @Ajax.ActionLink("Create New Database", "Create", null, new AjaxOptions { UpdateTargetId = "dbContent" }, new { @class = "btn btn-info" })
</p>
<table class="table table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
            {
        <tr>
            <td>
                @Ajax.ActionLink(item.Name, "Details", new { id = item.ID }, new AjaxOptions { UpdateTargetId = "tblContent" }, new { @class = "btn btn-link" })
            </td>
            <td class="text-right">
                <div class="btn-group" role="group">
                    @Html.ActionLink("Edit", "Edit", new { id = item.ID }, new { @class = "btn btn-warning" })
                    @Html.ActionLink("Delete", "Delete", new { id = item.ID }, new { @class = "btn btn-danger" })
                </div>
            </td>
        </tr>
    }

</table>